import "./globals.css";
import localFont from "next/font/local";

const allenoire = localFont({
  src: "./font/Allenoire-font.otf",
  variable: "--font-allenoire",
  style: "normal",
  weight: "700",
});
const lexend = localFont({
  src: "./font/Lexend-Light.ttf",
  variable: "--font-lexend",
  style: "normal",
  weight: "300",
});

export const metadata = {
  title: "NFT Website",
  description: "Generated by Shakil",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${allenoire.variable} ${lexend.variable}`}>
      <body>{children}</body>
    </html>
  );
}
